name: Compile installer

on:
  schedule:
    - cron: '13 14 * * *'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Mindustry version
        id: mindustry_version
        run: |
          release=`curl -s "https://api.github.com/repos/Anuken/Mindustry/releases/latest"`
          RELEASE_NAME=(`echo $release | jq -r '.name'`)
          VERSION=${RELEASE_NAME[0]}
          NUMBER=${RELEASE_NAME[2]}
          if [ ! `echo $NUMBER | grep -F .` ]; then NUMBER=$NUMBER.0; fi
          LONG_VERSION=$VERSION.$NUMBER
          RELEASE_PAGE=`echo $release | jq -r '.html_url'`

          echo $LONG_VERSION > version_cache

          store() { echo "::set-output name=$1::$2"; }
          store VERSION $VERSION
          store NUMBER $NUMBER
          store LONG_VERSION $LONG_VERSION
          store RELEASE_PAGE $RELEASE_PAGE

      - uses: actions/cache@v2
        id: cache
        with:
          path: version_cache
          key: mindustry-${{ steps.mindustry_version.outputs.LONG_VERSION }}

      - name: Apply versions to install.nsi
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sed -i 's/X.X/${{ steps.mindustry_version.outputs.VERSION }}/' install.nsi
          sed -i 's/Y.Y/${{ steps.mindustry_version.outputs.NUMBER }}/' install.nsi

      - name: Get game files from itch.io
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          post() { curl -s $1 -H 'Content-Type: application/x-www-form-urlencoded' --data-raw '' | jq -r .url; }
          download() { post 'https://anuke.itch.io/mindustry/file/'{$1} | xargs curl -JLOs; }
          URL=`post 'https://anuke.itch.io/mindustry/download_url'`
          ID=(`curl -s $URL | grep -oP '(?<=data-upload_id=").*?(?=")'`)
          download ${ID[0]} &
          download ${ID[1]} &
          wait
          for f in *.zip; do unzip -q -d "${f%*.zip}" "$f"; done

      - name: Add file deletion scripts for uninstaller
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir merged_files
          cp -r mindustry-windows-32-bit/* merged_files
          cp -r mindustry-windows-64-bit/* merged_files
          php .github/workflows/rewriter.php merged_files install.nsi new.nsi
          cat new.nsi

      - name: Create installer
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update -qq && sudo apt-get install -qq -y nsis > /dev/null
          makensis new.nsi

      - name: Create Release
        if: steps.cache.outputs.cache-hit != 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.mindustry_version.outputs.LONG_VERSION }}
          release_name: ${{ steps.mindustry_version.outputs.VERSION }} Build ${{ steps.mindustry_version.outputs.NUMBER }}
          body: |
            Release Mindustry ${{ steps.mindustry_version.outputs.VERSION }} Build ${{ steps.mindustry_version.outputs.NUMBER }}.
            You can see [github release page](${{ steps.mindustry_version.outputs.RELEASE_PAGE }}).

      - name: Upload Release Asset
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Mindustry_${{ steps.mindustry_version.outputs.VERSION }}_${{ steps.mindustry_version.outputs.NUMBER }}.exe
          asset_name: Mindustry_${{ steps.mindustry_version.outputs.VERSION }}_${{ steps.mindustry_version.outputs.NUMBER }}.exe
          asset_content_type: application/octet-stream
